### ISSUE TITLE
Can't use Google Meet Topbar

### ISSUE THREAD

**Issue by fmlatghor** [jcw-os/google-meet-ptt#8]
When I have the google-meet-ptt extension enabled, I can't click any of the icons in the top; chat, people, etc. What causes this and how can it be fixed.

**Comment by jackcw** [comment]
It appears Google has updated their interface and so the script is adding a background as a bug. I will try investigate over the weekend

**Comment by fmlatghor** [comment]
It looks like google added a shortcut to mute yourself, so I don't really see much for this project anymore. It would be nice if you could use the shortcut outside of the browser, but that would require doing something completely different. I might look into that.

**Comment by jackcw** [comment]
It appears to have sorted itself now @fmlatghor. Google must have reverted an update to fix the way they do the top bar. 

The shortcut has existed the whole time, I wouldnt say this is no longer necessary as the shortcut you'd have to press 2 keys each time to start and stop the mic instead of the intended use of this extension to to push to talk.
